In [ ]:
import numpy as np 
import matplotlib.pyplot as plt
from scipy.spatial.distance import cdist
np.random.seed(2)

means = [[2, 2], [4, 2]]
cov = [[.3, .2], [.2, .3]]
N = 10
X0 = np.random.multivariate_normal(means[0], cov, N).T
X1 = np.random.multivariate_normal(means[1], cov, N).T

X = np.concatenate((X0, X1), axis = 1)
y = np.concatenate((np.ones((1, N)), -1*np.ones((1, N))), axis = 1)
# Xbar 
# y = sgn(w0 + w1x1 + w2x2) = sgn(w.Xbar) = (w0, w1, w2) * (1, x1, x3)
X = np.concatenate((np.ones((1, 2*N)), X), axis = 0)

In [5]:
X.T

array([[1.        , 2.22096057, 2.19579728],
       [1.        , 2.70132234, 3.43487375],
       [1.        , 3.08493823, 2.70849736],
       [1.        , 2.02701417, 1.47010441],
       [1.        , 2.73223639, 2.32571583],
       [1.        , 1.21171968, 2.23682627],
       [1.        , 2.22920603, 1.72925457],
       [1.        , 1.8637762 , 1.59716548],
       [1.        , 1.74682699, 2.27230351],
       [1.        , 2.37191737, 2.37595358],
       [1.        , 4.47403369, 2.4040742 ],
       [1.        , 4.09281249, 1.65061706],
       [1.        , 4.22222334, 2.11659863],
       [1.        , 4.58438569, 2.05326933],
       [1.        , 4.74493118, 2.67628604],
       [1.        , 3.6355797 , 2.63347726],
       [1.        , 5.19217738, 3.2425902 ],
       [1.        , 3.51075436, 2.11880111],
       [1.        , 3.93784332, 1.56029947],
       [1.        , 3.8787214 , 2.12126884]])

In [6]:
y.T

array([[ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [ 1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.],
       [-1.]])

In [7]:
def h(w, x):    
    # w1*x1 + w2*x2...+ w0
    return np.sign(np.dot(w.T, x))

def has_converged(X, y, w):
    # Kiểm tra hội tụ
    return np.array_equal(h(w, X), y) 

def perceptron(X, y, w_init):
    w = [w_init]
    N = X.shape[1]
    d = X.shape[0]
    mis_points = []
    while True:
        # mix data 
        mix_id = np.random.permutation(N)
        for i in range(N):
            xi = X[:, mix_id[i]].reshape(d, 1)
            yi = y[0, mix_id[i]]
            if h(w[-1], xi)[0] != yi: # misclassified point
                mis_points.append(mix_id[i])
                w_new = w[-1] + yi*xi 
                w.append(w_new)
                
        if has_converged(X, y, w[-1]):
            break
    return (w, mis_points)

In [8]:
d = X.shape[0]
w_init = np.random.randn(d, 1)
(w, m) = perceptron(X, y, w_init)

In [12]:
w[-1]

array([[ 3.6864918 ],
       [-4.08776229],
       [ 4.1502239 ]])